### ISSUE TITLE
wfo returning concerning warnings 

### ISSUE THREAD

**Issue by jtmiller28** [globalbioticinteractions/nomer#103] opened 2022-09-13 13:55 UTC
using wfo via nomer with the following command: 

cat combined-names-for-WFO.tsv | nomer append wfo --include-header > name-wfo.tsv 

produced warnings: 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mapdb.SerializerPojo$FieldInfo (file:/usr/local/bin/nomer) to field java.util.Collections$SingletonList.element
WARNING: Please consider reporting this to the maintainers of org.mapdb.SerializerPojo$FieldInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Not sure if these warnings are concerning, or if something is not aligning with my name file. Attaching .txt file used for resolution 
[combined-names-for-WFO.txt](https://github.com/globalbioticinteractions/nomer/files/9557774/combined-names-for-WFO.txt)

text file was modified into a .tsv using the following code: 

cat combined-names-for-WFO.txt | sed 's/^/\t/g' > combined-names-for-WFO.tsv

**Comment by jhpoelen** [comment] 2022-09-13 13:56
@jtmiller28 thanks for sharing! 

Please share the version of java you are using by:

sharing the results of:

java -version

**Comment by jtmiller28** [comment] 2022-09-13 13:57
java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

**Comment by jhpoelen** [comment] 2022-09-13 13:58
See related issue https://github.com/globalbioticinteractions/nomer/issues/44 .

**Comment by jhpoelen** [comment] 2022-09-13 14:03
oh, and the name alignment should work as expected. If not, please let me know, and share some specific examples of unexpected behavior.

**Comment by jtmiller28** [comment] 2022-09-13 14:04
Yes, that does appear to be the same issue. Should a different v. of java be used while accessing Nomer at the moment? I'm going to address some concerns I have with name alignment in a separate issue if that is fine.

**Comment by jhpoelen** [comment] 2022-09-13 14:25
Ok, thanks for checking. I'll close this issue because it is a duplicate of #44 . 

And, I'll have a look whether an upgrade to a more recent version of mapdb is feasible.

I use java8 so I don't see the warnings. 

>  I'm going to address some concerns I have with name alignment in a separate issue if that is fine.

yes, please do share your concerns with the name mapping in a separate issue.

**Closed by jhpoelen** 2022-09-13 14:25 UTC
