### ISSUE TITLE
Lucene lock obtain timed out exception

### ISSUE THREAD

**Issue by nleguillarme** [globalbioticinteractions/nomer#31] opened 2021-02-03 16:21 UTC
Hi @jhpoelen.

I have a big bunch of names and ids I want to check/resolve/convert using nomer, so I would like to handle them concurrently.

Nomer is called by a Flask app served by a Gunicorn server to handle multiple requests efficiently, and to test the whole thing, I start several python threads sending "append globi-taxon-cache" requests.

Sometimes, however, nomer returns the following exception :

java.lang.RuntimeException: failed to create indexWriter, cannot continue
	at org.eol.globi.taxon.TaxonLookupServiceImpl.start(TaxonLookupServiceImpl.java:176)
	at org.eol.globi.taxon.TaxonCacheService$1.<init>(TaxonCacheService.java:147)
	at org.eol.globi.taxon.TaxonCacheService.initTaxonIdMap(TaxonCacheService.java:145)
	at org.eol.globi.taxon.TaxonCacheService.init(TaxonCacheService.java:137)
	at org.eol.globi.taxon.TaxonCacheService.lazyInit(TaxonCacheService.java:131)
	at org.eol.globi.taxon.TaxonCacheService.match(TaxonCacheService.java:219)
	at org.eol.globi.service.TermMatcherHierarchical.match(TermMatcherHierarchical.java:57)
	at org.globalbioticinteractions.nomer.util.AppendingRowHandler.onRow(AppendingRowHandler.java:30)
	at org.globalbioticinteractions.nomer.util.MatchUtil.apply(MatchUtil.java:52)
	at org.globalbioticinteractions.nomer.util.MatchUtil.match(MatchUtil.java:26)
	at org.globalbioticinteractions.nomer.cmd.CmdAppend.run(CmdAppend.java:38)
	at org.globalbioticinteractions.nomer.cmd.CmdLine.run(CmdLine.java:18)
	at org.globalbioticinteractions.nomer.cmd.CmdLine.run(CmdLine.java:27)
	at org.globalbioticinteractions.nomer.Nomer.main(Nomer.java:15)
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/pynomer/.nomer/term-cache/lucene/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:84)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1098)
	at org.eol.globi.taxon.TaxonLookupServiceImpl.start(TaxonLookupServiceImpl.java:174)
	... 13 more
 
I guess this is a problem of concurrent access to the cache. Do you think there is any way to make nomer work in this situation ?
Thanks

**Comment by jhpoelen** [comment] 2021-02-03 16:26
@nleguillarme great to hear that you are starting to use concurrent requests! Can you please share code that you use to invoke the concurrent requests? Ideally, I'd like to be able to reproduce the issue independently, so I can see whether a proposed fix works as designed.

**Comment by nleguillarme** [comment] 2021-02-03 17:22
@jhpoelen

Clone pynomer's repo and install pynomer :
`git clone https://github.com/nleguillarme/pynomer.git`
`cd pynomer`
`python setup.py sdist ; pip install dist/pynomer-0.1.6.tar.gz`

Build the docker image :
`docker build -t pynomer-server -f Dockerfile.gunicorn .`

Start the server :
`docker run -v${PWD}/.nomer:/pynomer/.nomer -v${PWD}/logs:/logs -p 8180:8180 pynomer-server

In another terminal, run the attached script test_pynomer.py
`python test_pynomer.py`

[taxons.csv.txt](https://github.com/globalbioticinteractions/nomer/files/5920308/taxons.csv.txt)
[test_pynomer.py.txt](https://github.com/globalbioticinteractions/nomer/files/5920309/test_pynomer.py.txt)

**Comment by jhpoelen** [comment] 2021-02-04 22:13
@nleguillarme thanks for providing the extra info. 

The likely root cause is multiple nomer instances trying to rebuild a search index locally at the same location. 

As I am working on a fix, a workaround is to resolve one term using one nomer instance first. Only after nomer is initialized automatically before the first term is resolved, start the massively paralell operation. Alternatively, you can start separate nomer instances using different cache dirs.

Thanks again for reporting this issue and I hope to get to it sooner rather than later.  

PS Why not use ```parallel``` (https://opensource.com/article/18/5/gnu-parallel) to do parallel resolving of terms?

```
$ cat taxa.tsv | parallel nomer append > taxon-matches.tsv
```

**Comment by nleguillarme** [comment] 2021-02-05 13:26
> The likely root cause is multiple nomer instances trying to rebuild a search index locally at the same location.

I don't think this is the cause of the problem. I've just checked by building the index first, then starting the threads (the server having access to the built index in the .nomer directory), and I still have the LockObtainFailedException. I am wondering why nomer tries to obtain a write lock at query time ? Does it have to write something in the index at each query ?

> PS Why not use `parallel` (https://opensource.com/article/18/5/gnu-parallel) to do parallel resolving of terms?

I didn't know about GNU Parallel, I'll take a look at it, thanks.

**Comment by nleguillarme** [comment] 2021-02-05 14:37
I've just benchmarked GNU Parallel against my other ways of calling nomer... and it's incredibly fast !!!
~441k taxa matched in 36s

I guess I won't need my whole webserver thing anymore, just nomer in a docker container with GNU Parallel installed... I'll try that right away. Thank you for the tip.

**Comment by jhpoelen** [comment] 2021-02-05 17:58
@nleguillarme glad to hear that using ```parallel``` looks promising for what you are trying to do.

And, yes, you were right that the write lock occurs even at query time, after building the index. I reproduced and fixed the issue and hoping to release a new nomer version soon. Thanks for being patient.

**Comment by nleguillarme** [comment] 2021-02-10 17:51
It turned out that I didn't even need parallel, as I use Apache Airflow which already has some mechanisms to run tasks in parallel.
What has considerably accelerated the matching process is batch query processing, i.e. the ability to ask for several taxons at once using the "cat taxa.tsv | nomer" mechanism. I didn't know it was possible, and it's a real life saver ;)

**Comment by jhpoelen** [comment] 2021-02-16 20:16
@nleguillarme I released a new version of nomer v0.1.23 for fix for the Lucene lock issue you reported  at https://github.com/globalbioticinteractions/nomer/releases/tag/0.1.23 . 

Thanks for being patient and let me know if your issue has been resolved.

**Comment by jhpoelen** [comment] 2021-03-03 23:36
@nleguillarme did you get a chance to confirm that the lucene lock timeout has been resolved for you. If I don't hear from you in the next weeks, I assume that the issue has been resolved. Thanks for being patient.

**Closed** 2021-03-11 21:21 UTC
