### ISSUE TITLE
Discoverlife subgenus names

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/nomer#134] opened 2022-12-09 22:54 UTC
Discoverlife catalog does not include subgenera because they are located on a different webpage than the indexed catalog.

From the online version of the checklist found here
https://www.discoverlife.org/mp/20q?act=x_checklist&guide=Apoidea_species&flags=HAS:

Subgenus is only located on a different webpage. So for _Bombus vosnesenskii_  Radoszkowski, 1862 should equal _Bombus_ (_Pyrobombus_) _vosnesenskii_ Radoszkowski, 1862

![Screen Shot 2022-12-09 at 2 40 53 PM](https://user-images.githubusercontent.com/1044474/206808236-aefde127-cdad-47e1-b29f-2f347a9cd224.png)

**Comment by jhpoelen** [comment] 2023-05-03 22:38
@seltmann was just looking at adding subspecies to DiscoverLife taxonomic alignment. 

```
curl --insecure "https://www.discoverlife.org/mp/20q?search=Bombus+vosnesenskii&guide=1&flags=HAS:"\
 tee Bombus+vosnesenskii.html
```

yielded attached file. 
[Bombus+vosnesenskii.html.txt](https://github.com/globalbioticinteractions/nomer/files/11391686/Bombus%2Bvosnesenskii.html.txt)


and the subgenus appears present - 

```
cat Bombus+vosnesenskii.html | grep Pyro
<br><small>Subgenus: <a href="/mp/20p?see=Pyrobombus&name=Bombus&guide=1&flags=HAS:subgenus:"><i>Pyrobombus</i></a></small>
```

**Comment by jhpoelen** [comment] 2023-05-03 22:38
This would mean that I'd have to ask discoverlife 20k times for their separate species pages. Is there a more efficient way to get this?

**Comment by jhpoelen** [comment] 2023-05-03 22:45
also, note that DiscoverLife keeps associations with specimen records that appear to contain more information (e.g., associatedTaxa) that those shared with GBIF, or some not shared at all. Is this a known issue? 

For instance, https://www.discoverlife.org/mp/20l?id=BBSL154071;BBSL154070;BBSL__BBSLID87119 (see attached screenshot) contains associatedTaxa information. 

![image](https://user-images.githubusercontent.com/1084872/236066973-0b317f3a-6c6b-4476-9043-6417f9c33bbe.png)


However, on the associated GBIF occurrence page at https://www.gbif.org/occurrence/658974260 (see attached screenshot) no such associatedTaxa can be found. 

![image](https://user-images.githubusercontent.com/1084872/236066894-bbbc742d-9161-4e85-a94b-f44016d91870.png)

**Comment by jhpoelen** [comment] 2024-05-02 18:23
duplicate of #161 .

**Closed by jhpoelen** 2024-05-02 18:23 UTC
Labels: Big-Bee
